<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 19:58:59
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 23:06:38
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 23:37:57
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 23:38:25
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 23:38:30
*/
?>
<?php  exit();
/*
Page: /
Error: 无法使用数据库
Time2012-12-04 23:38:51
*/
?>
